export const redirects = {
  '/start/download-and-install/': '/start/install/',
  '/start/verify-a-download/': '/start/install/#verify-your-download',
  '/start/first-run/': '/start/turn-jensen-on/',
  '/ai/how-it-works/': '/assistant/how-it-works/',
  '/ai/context-server/': '/assistant/how-it-works/#what-your-assistant-gets-on-connect',
  '/ai/choosing-an-assistant/': '/assistant/choosing-an-assistant/',
  '/ai/models-and-providers/': '/assistant/models-and-providers/',
  '/ai/what-your-assistant-can-do/': '/reference/assistant-tools/',
  '/ai/plans-and-objectives/': '/flow/plans/',
  '/ai/profiles-and-workflows/': '/flow/workflows/',
  '/ai/agent-hooks/': '/automation/agent-hooks/',
  '/ai/missions-and-schedules/': '/automation/specialists/',
  '/ai/trust-approvals-and-permissions/': '/safety/trust-and-permissions/',
  '/safety/findings-and-screening/': '/knowledge/findings/',
  '/app/project/': '/app/project-graph/',
  '/app/work/': '/app/notes/',
  '/automation/plans-and-objectives/': '/flow/plans/',
  '/automation/workflows/': '/flow/workflows/',
  '/automation/profiles-and-missions/': '/automation/specialists/',
}
